### PR TITLE
Fixed some issues in Problem that may become important

### PR DESCRIPTION
**Pull request by JKohlman**
Fixed problem in Problem that occurred when lower-casing, added jest dependency and java 1.8 compat in build.gradle, added INTERNET app permission and uses-library fix in manifest, insertProblem works with elastic search (mostly), moved ElasticSearchControllerTest to androidTest so it runs on app.

### CODE REVIEW

**Comment by DalinRiches** [comment]
Hey so I've noticed you've added jest into Problem class, kinda opposed to this as it breaks the dependency rule by making problem reliant on the framework we are using for the remote database. Is there any way we could have the problemRepo take care of this?

**Comment by DalinRiches** [comment]
For example creating a database model that has all the JEST annotations and a mapper that maps the domain level problem to the database level JestProblem

**Comment by JKohlman** [comment]
I was just following the example used in the lab with lonelytwitter and they did it. That value just represents the problems unique ID in ElasticSearch and probably can disappear at some point as we'll likely be using our own unique IDs

**Comment by JKohlman** [comment]
Actually we can probably use that and just set that as the problems ID on creation as it should be unique

**Comment by DalinRiches** [comment]
No your doing it the right way, jest will need that information, but adding jest annotations to the domain makes the domain dependent on jest, which we can't have. 

I'm saying the ProblemRepo class should take in the domain level Problem which is pure java and convert it to a "DataProblem" or something which has the required jest annotations or SQL annotations etc.

**Comment by JKohlman** [comment]
Will remove JEST from problem

**Pull request closed without merging**
